import { Employee } from "./types";

export const data: Employee[] = [
  {
    id: 1,
    firstName: "Peter",
    lastName: "Gibbons",
    department: "Engineering",
    dateStarted: "1997-03-13T00:00:00.000Z",
    quote:
      "The thing is, Bob, it's not that I'm lazy, it's that I just don't care.",
  },
  {
    id: 2,
    firstName: "Samir",
    lastName: "Nagheenanajar",
    department: "Engineering",
    dateStarted: "1998-06-25T00:00:00.000Z",
    quote: "No one in this country can ever pronounce my name right.",
  },
  {
    id: 3,
    firstName: "Micheal",
    lastName: "Bolton",
    department: "Engineering",
    dateStarted: "1998-10-01T00:00:00.000Z",
    quote: "That's the worst idea I've ever heard in my life, Tom.",
  },
  {
    id: 4,
    firstName: "Bill",
    lastName: "Lumbergh",
    department: "Management",
    dateStarted: "1996-08-15T00:00:00.000Z",
    quote: "Ummm, I'm gonna need you to go ahead come in tomorrow.",
  },
  {
    id: 5,
    firstName: "Bob",
    lastName: "Slydell",
    department: "Management",
    dateStarted: "1997-06-13T00:00:00.000Z",
    quote: "What would you say...you do here?",
  },
  {
    id: 6,
    firstName: "Bob",
    lastName: "Porter",
    department: "Management",
    dateStarted: "1997-07-30T00:00:00.000Z",
    quote: "We need to talk about your TPS reports.",
  },
  {
    id: 7,
    firstName: "Dom",
    lastName: "Portwood",
    department: "Management",
    dateStarted: "1996-05-05T00:00:00.000Z",
    quote: "Looks like you've been missing a lot of work lately.",
  },
  {
    id: 8,
    firstName: "Jane",
    lastName: "Anderson",
    department: "Operations",
    dateStarted: "1999-01-22T00:00:00.000Z",
    quote: "Uh-oh. Sounds like somebody's got a case of the Mondays.",
  },
  {
    id: 9,
    firstName: "Tom",
    lastName: "Smykowski",
    department: "Operations",
    dateStarted: "1997-04-13T00:00:00.000Z",
    quote: "I have people skills; I am good at dealing with people.",
  },
  {
    id: 10,
    firstName: "Nina",
    lastName: "Schultz",
    department: "Operations",
    dateStarted: "1999-02-16T00:00:00.000Z",
    quote: "Corporate accounts payable, Nina speaking. *JUST* a moment.",
  },
  {
    id: 11,
    firstName: "Milton",
    lastName: "Waddams",
    department: "Operations",
    dateStarted: "1995-04-18T00:00:00.000Z",
    quote: "Excuse me, I believe you have my stapler...",
  },
  {
    id: 12,
    firstName: "Stan",
    lastName: "Adams",
    department: "Food Services",
    dateStarted: "1997-11-01T00:00:00.000Z",
    quote: "We need to talk about your flair.",
  },
  {
    id: 13,
    firstName: "Joanna",
    lastName: "Baker",
    department: "Food Services",
    dateStarted: "1998-09-18T00:00:00.000Z",
    quote:
      "I do want to express myself, okay. And I don't need 37 pieces of flair to do it.",
  },
  {
    id: 14,
    firstName: "Brian",
    lastName: "Flores",
    department: "Food Services",
    dateStarted: "1998-12-25T00:00:00.000Z",
    quote: "Some Pizza Shooters, Shrimp Poppers, or Extreme Fajitas?",
  },
];
